export const GET_SELECTED_INGREDIENTS = 'GET_SELECTED_INGREDIENTS'
export const ADD_SELECTED_INGREDIENT = 'ADD_SELECTED_INGREDIENT'
export const DROP_SELECTED_INGREDIENT = 'DROP_SELECTED_INGREDIENT'
export const SET_SORT_INDEX_ELEMENT = 'SET_SORT_INDEX_ELEMENT'